//Shop...
export const SET_SHOP_NAME = "SET_SHOP_NAME"

//List...
export const SET_ITEM_HISTORY_ACTIONS = "SET_ITEM_HISTORY_ACTIONS"
export const ADD_ITEM_HISTORY_ACTIONS = "ADD_ITEM_HISTORY_ACTIONS"
export const REMOVE_ITEM_HISTORY_ACTIONS = "REMOVE_ITEM_HISTORY_ACTIONS"
export const CLEAM_LIST_HISTORY_ACTIONS = "CLEAM_LIST_HISTORY_ACTIONS"

//Navigation...
export const SET_PAGE = "SET_PAGE"

//Handles...
export const SET_HANDLE = "SET_HANDLE"
export const DELETE_HANDLE = "DELETE_HANDLE"

//Loading...
export const SET_LOADING = "SET_LOADING"